package com.wn32.mapper;

import com.wn32.model.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    int updateByPrimaryKey(User record);

    User findfindUserByName(String userName);

}