package com.wn32.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuId
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    private Integer stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuName
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    private String stuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuAge
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    private Integer stuage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuGender
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    private String stugender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuId
     *
     * @return the value of student.stuId
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public Integer getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuId
     *
     * @param stuid the value for student.stuId
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public void setStuid(Integer stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuName
     *
     * @return the value of student.stuName
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuName
     *
     * @param stuname the value for student.stuName
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuAge
     *
     * @return the value of student.stuAge
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public Integer getStuage() {
        return stuage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuAge
     *
     * @param stuage the value for student.stuAge
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public void setStuage(Integer stuage) {
        this.stuage = stuage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuGender
     *
     * @return the value of student.stuGender
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public String getStugender() {
        return stugender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuGender
     *
     * @param stugender the value for student.stuGender
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public void setStugender(String stugender) {
        this.stugender = stugender == null ? null : stugender.trim();
    }
}