package com.wn32.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.user_id
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.user_name
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.user_gender
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    private String userGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.user_age
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    private Integer userAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _user.user_pwd
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    private String userPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.user_id
     *
     * @return the value of _user.user_id
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.user_id
     *
     * @param userId the value for _user.user_id
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.user_name
     *
     * @return the value of _user.user_name
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.user_name
     *
     * @param userName the value for _user.user_name
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.user_gender
     *
     * @return the value of _user.user_gender
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.user_gender
     *
     * @param userGender the value for _user.user_gender
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.user_age
     *
     * @return the value of _user.user_age
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.user_age
     *
     * @param userAge the value for _user.user_age
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _user.user_pwd
     *
     * @return the value of _user.user_pwd
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _user.user_pwd
     *
     * @param userPwd the value for _user.user_pwd
     *
     * @mbg.generated Fri Jan 08 16:17:26 CST 2021
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }
}